# Generated by Django 2.0.5 on 2018-05-05 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_ex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prize',
            name='winner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
