# Generated by Django 2.0.5 on 2018-05-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ex', '0002_userreceiptprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
